"""Structured learned rules with provenance, lifecycle, dedup, and validation.

Rules live as an append-only JSONL store at ``<harness_root>/rules.jsonl``
(the latest record per rule id wins, so retiring a rule appends an updated
record rather than rewriting the file). Read-only task-facing rules are rendered
from that store as an agent skill::

    rules.md            skill-style task guide plus compact generated scope
                        index. Contains NO rule text.
    rules/global.md     the default: broadly reusable rules
    rules/<topic>.md    a meaningful context chosen by managed repair
    rules/scoped.md     the fallback for specific rules with no stable name

The split keeps learned content out of the task-agent context until the agent
chooses a read/search tool. ``scope`` is a reasoned managed-repair decision made
from the evidence it already holds (see :mod:`.scopes` for what the two reserved
names mean); host scope hints inform that decision but never dictate it.

Retrieval stays **per rule** over ``rules.jsonl`` (see
:meth:`RulesStore.relevant`), not per file, so workspace organization cannot
degrade which rules get selected.

Lifecycle (evidence before trust)::

    candidate ──(validated: metric improved)──▶ active
        │
        └────────(invalidated: no improvement / regressed)──▶ retired
    active ──(regression validation or operator retires it)──▶ retired

When ``config.rule_validation`` is on, :meth:`RulesStore.add` records a
**candidate**. It is immediately discoverable and clearly labeled provisional,
but is never automatically injected; only a validator verdict promotes it to
``active``. When the flag is off, rules enter ``active`` immediately.

This addresses rule rot with deterministic novelty suppression and
:meth:`RulesStore.effectiveness`, which gives the reflection cycle before/after
notice counts per rule from the journal. An optional host-configured count bound
remains available, but there is no arbitrary default global cap.

All methods are synchronous blocking I/O; async callers wrap them in
``asyncio.to_thread``.
"""

from __future__ import annotations

import importlib.resources
import re
import threading
import uuid
from collections.abc import Callable, Iterable, Mapping, Sequence
from dataclasses import dataclass, replace
from datetime import UTC, datetime
from functools import lru_cache
from pathlib import Path
from typing import Any, Literal, cast

from ..config import HarnessConfig
from ._io import append_jsonl, atomic_write_json, atomic_write_text, load_json, read_jsonl
from .journal import Journal
from .mailbox import DiagnosticNotice
from .sanitize import sanitize_text
from .scopes import (
    GLOBAL_SCOPE,
    RESERVED_SCOPES,
    SCOPED_SCOPE,
    normalize_scope,
    normalize_scope_description,
    validate_scope,
)

__all__ = [
    "GLOBAL_SCOPE",
    "RESERVED_SCOPES",
    "SCOPED_SCOPE",
    "Rule",
    "RuleApplicability",
    "RuleStatus",
    "RulesCapError",
    "RulesStore",
    "TrialState",
    "derive_notice_tags",
    "normalize_scope",
    "normalize_scope_description",
    "validate_scope",
]

_TEMPLATE_PACKAGE = "pandaprobe_harness.filesystem.templates"
_TEMPLATE_NAME = "rules.md"
#: Everything in the skill-root template up to (and including) this line is
#: preserved verbatim; the generated References directory is rendered below it.
REFERENCES_MARKER = "<!-- REFERENCES — generated by the harness; do not edit below -->"
#: Heading that separates unproven candidate rules from validated active ones.
PROVISIONAL_HEADING = "### Provisional rules (under evaluation)"
_PROVISIONAL_NOTE = (
    "_The following candidate rules are available but not yet validated. Treat\n"
    "them as tentative and prefer validated rules when they conflict._"
)

RuleStatus = Literal["candidate", "active", "retired"]
RuleApplicability = Literal["global", "topical", "task"]

#: Journal `notice` events scanned to estimate a candidate's pre-trial baseline.
_BASELINE_WINDOW = 200
#: Bounds applied to rule tags (both derived and repair-supplied).
_TAG_MAX_COUNT = 16
_TAG_MAX_LEN = 48


class RulesCapError(RuntimeError):
    """Raised when adding a rule would exceed the live-rule cap."""


def _as_status(value: object) -> RuleStatus:
    """Forgiving status parse; unknown values degrade to ``active``.

    ``candidate`` must round-trip: a persisted candidate that silently read
    back as ``active`` would self-promote across process restarts.
    """

    if value == "candidate":
        return "candidate"
    if value == "retired":
        return "retired"
    return "active"


def _utcnow_iso() -> str:
    return datetime.now(UTC).isoformat()


def _clean_tags(values: Iterable[str]) -> tuple[str, ...]:
    """Normalize tags: casefold, strip, dedup (order kept), bounded count/length."""

    tags: list[str] = []
    for value in values:
        cleaned = value.strip().casefold()[:_TAG_MAX_LEN]
        if cleaned and cleaned not in tags:
            tags.append(cleaned)
        if len(tags) >= _TAG_MAX_COUNT:
            break
    return tuple(tags)


def derive_notice_tags(notice: DiagnosticNotice) -> tuple[str, ...]:
    """Retrieval tags for a rule learned from ``notice``.

    Signatures, metric names, per-trace signal names, and the severity — the
    lexical hooks a later query (pending-notice signatures + task hint) can
    match against.
    """

    raw: list[str] = list(notice.signatures)
    raw += [metric.name for metric in notice.metrics]
    for signals in notice.signal_breakdown.values():
        raw += [str(name) for name in signals]
    raw.append(notice.severity)
    return _clean_tags(raw)


#: Lexical retrieval tokenizer: word-ish tokens, casefolded, ≥2 chars. ":"
#: splits signatures ("breach:tool_correctness" → breach + tool_correctness)
#: while "_" keeps metric names whole.
_TOKEN_RE = re.compile(r"[a-z0-9_]+")


def _tokenize(text: str) -> frozenset[str]:
    return frozenset(t for t in _TOKEN_RE.findall(text.casefold()) if len(t) >= 2)


_NOVELTY_STOPWORDS = frozenset(
    {
        "a", "an", "and", "as", "at", "be", "before", "by", "for", "from",
        "if", "in", "into", "is", "it", "of", "on", "only", "or", "the",
        "then", "to", "use", "when", "with", "task", "tasks", "workflow",
    }
)
_GENERIC_NOVELTY_TAGS = frozenset(
    {
        "active", "argument_correctness", "breach", "candidate", "coherence",
        "global", "provisional", "scoped", "task_completion", "tool_correctness",
        "trend",
    }
)


def _novelty_tokens(text: str) -> frozenset[str]:
    return _tokenize(text) - _NOVELTY_STOPWORDS


def _overlap(left: frozenset[str], right: frozenset[str]) -> tuple[float, float]:
    if not left or not right:
        return 0.0, 0.0
    shared = len(left & right)
    return shared / len(left | right), shared / min(len(left), len(right))


def _coverage_reason(
    existing: Rule,
    *,
    text: str,
    scope: str,
    tags: Sequence[str],
    failure_signatures: Sequence[str],
) -> str | None:
    if RulesStore._normalize(existing.rule) == RulesStore._normalize(text):
        return "exact_text"
    if existing.scope != scope:
        return None

    similarity, containment = _overlap(
        _novelty_tokens(existing.rule), _novelty_tokens(text)
    )
    if similarity >= 0.72 or containment >= 0.88:
        return "near_duplicate_text"

    proposed_signatures = frozenset(str(value) for value in failure_signatures)
    existing_signatures = frozenset(existing.failure_signatures)
    same_failure = bool(proposed_signatures & existing_signatures)
    if same_failure and (similarity >= 0.30 or containment >= 0.55):
        return "covered_failure_signature"

    proposed_tags = frozenset(_clean_tags(tags)) - _GENERIC_NOVELTY_TAGS
    existing_tags = frozenset(existing.tags) - _GENERIC_NOVELTY_TAGS
    meaningful_tag_overlap = {
        tag for tag in proposed_tags & existing_tags if ":" not in tag
    }
    if len(meaningful_tag_overlap) >= 2 and (
        similarity >= 0.40 or containment >= 0.65
    ):
        return "covered_tags"
    return None


def _relevance(rule: Rule, query_tokens: frozenset[str]) -> float:
    """Weighted token overlap, normalized by query size.

    Tag hits count double (tags are curated retrieval hooks); rule/rationale/
    metric text hits count once. Plain bounded overlap keeps retrieval
    deterministic and dependency-free; callers cap the returned result set.
    """

    if not query_tokens:
        return 0.0
    tag_tokens: frozenset[str] = frozenset()
    for tag in rule.tags:
        tag_tokens |= _tokenize(tag)
    text_tokens = (
        _tokenize(rule.rule) | _tokenize(rule.rationale) | _tokenize(rule.metric or "")
    )
    tag_hits = len(query_tokens & tag_tokens)
    text_hits = len(query_tokens & (text_tokens - tag_tokens))
    return (2.0 * tag_hits + float(text_hits)) / len(query_tokens)


def _rank(rules: list[Rule], scores: dict[str, float]) -> list[Rule]:
    """Order by score desc, then recency desc, then id asc (stable sorts)."""

    ranked = sorted(rules, key=lambda r: r.id)
    ranked.sort(key=lambda r: r.created_at, reverse=True)
    ranked.sort(key=lambda r: scores[r.id], reverse=True)
    return ranked


def _matches_metric_family(signatures: Sequence[str], metric: str | None) -> bool:
    """Whether any signature belongs to the metric's condition family.

    Signatures look like ``breach:tool_correctness``; the family is "any
    condition on this metric". With no metric, any signature at all matches.
    """

    if metric is None:
        return bool(signatures)
    suffix = f":{metric}"
    return any(signature.endswith(suffix) for signature in signatures)


@dataclass(frozen=True, slots=True)
class TrialState:
    """Validation bookkeeping for a candidate rule (forgiving JSON).

    The baseline is the pre-candidate breach rate for the rule's metric
    family, estimated from recent journal notices at add time; the trial
    counts distinct sessions observed (and breached) while the candidate is live.
    """

    baseline_breached_sessions: int = 0
    baseline_sessions: int = 0
    baseline_window: int = 0
    trial_started_at: str = ""
    observed_sessions: tuple[str, ...] = ()
    breached_sessions: tuple[str, ...] = ()
    replay_attempts: int = 0
    verdict: str = ""

    @property
    def baseline_rate(self) -> float:
        """Pre-candidate breach rate; 1.0 when nothing was journaled (the rule
        was authored in response to a live failure — assume it was firing)."""

        if self.baseline_sessions <= 0:
            return 1.0
        return self.baseline_breached_sessions / self.baseline_sessions

    @property
    def trial_rate(self) -> float:
        if not self.observed_sessions:
            return 0.0
        return len(self.breached_sessions) / len(self.observed_sessions)

    def to_json(self) -> dict[str, Any]:
        return {
            "baseline_breached_sessions": self.baseline_breached_sessions,
            "baseline_sessions": self.baseline_sessions,
            "baseline_window": self.baseline_window,
            "trial_started_at": self.trial_started_at,
            "observed_sessions": list(self.observed_sessions),
            "breached_sessions": list(self.breached_sessions),
            "observed_breaches": len(self.breached_sessions),
            "replay_attempts": self.replay_attempts,
            "verdict": self.verdict,
        }

    @classmethod
    def from_json(cls, data: dict[str, Any]) -> TrialState:
        def _int(key: str) -> int:
            raw = data.get(key)
            return raw if isinstance(raw, int) else 0

        def _str_tuple(key: str) -> tuple[str, ...]:
            raw = data.get(key)
            return tuple(str(item) for item in raw) if isinstance(raw, list) else ()

        return cls(
            baseline_breached_sessions=_int("baseline_breached_sessions"),
            baseline_sessions=_int("baseline_sessions"),
            baseline_window=_int("baseline_window"),
            trial_started_at=str(data.get("trial_started_at", "")),
            observed_sessions=_str_tuple("observed_sessions"),
            breached_sessions=_str_tuple("breached_sessions"),
            replay_attempts=_int("replay_attempts"),
            verdict=str(data.get("verdict", "")),
        )


@dataclass(frozen=True, slots=True)
class Rule:
    """One learned operating rule, with provenance and lifecycle."""

    id: str
    created_at: str
    rule: str
    rationale: str
    source_notice_id: str | None = None
    metric: str | None = None
    status: RuleStatus = "active"
    tags: tuple[str, ...] = ()
    trial: TrialState | None = None
    #: Which ``rules/<scope>.md`` file this rule lives in. ``global`` rules are
    #: always eligible for retrieval.
    scope: str = GLOBAL_SCOPE
    #: Applicability is independent of the topical file used for discovery.
    applicability: RuleApplicability = "global"
    #: Stable evaluator signatures used by deterministic novelty checks.
    failure_signatures: tuple[str, ...] = ()

    @staticmethod
    def new_id() -> str:
        return f"r-{uuid.uuid4().hex[:10]}"

    def to_json(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "created_at": self.created_at,
            "rule": self.rule,
            "rationale": self.rationale,
            "source_notice_id": self.source_notice_id,
            "metric": self.metric,
            "status": self.status,
            "tags": list(self.tags),
            "trial": self.trial.to_json() if self.trial is not None else None,
            "scope": self.scope,
            "applicability": self.applicability,
            "failure_signatures": list(self.failure_signatures),
        }

    @classmethod
    def from_json(cls, data: dict[str, Any]) -> Rule:
        tags = data.get("tags")
        trial = data.get("trial")
        clean_tags = tuple(str(t) for t in tags) if isinstance(tags, list) else ()
        # A record without a scope takes the default, like any other unspecified
        # field. Forgiving readers keep an older store loadable; they do not
        # reconstruct a scope nobody recorded.
        scope = normalize_scope(str(data["scope"])) if data.get("scope") else GLOBAL_SCOPE
        raw_applicability = data.get("applicability")
        if raw_applicability in {"global", "topical", "task"}:
            applicability = cast(RuleApplicability, raw_applicability)
        elif scope == GLOBAL_SCOPE:
            applicability = "global"
        elif scope == SCOPED_SCOPE:
            applicability = "task"
        else:
            applicability = "topical"
        raw_signatures = data.get("failure_signatures")
        failure_signatures = (
            tuple(str(value) for value in raw_signatures[:16])
            if isinstance(raw_signatures, list)
            else ()
        )
        return cls(
            id=str(data.get("id", "")),
            created_at=str(data.get("created_at", "")),
            rule=str(data.get("rule", "")),
            rationale=str(data.get("rationale", "")),
            source_notice_id=(
                str(data["source_notice_id"])
                if data.get("source_notice_id") is not None
                else None
            ),
            metric=str(data["metric"]) if data.get("metric") is not None else None,
            status=_as_status(data.get("status")),
            tags=clean_tags,
            trial=TrialState.from_json(trial) if isinstance(trial, dict) else None,
            scope=scope,
            applicability=applicability,
            failure_signatures=failure_signatures,
        )


class RulesStore:
    """Structured rules + rendered task-facing ``rules.md``."""

    def __init__(
        self,
        config: HarnessConfig,
        *,
        journal: Journal | None = None,
        visible_candidate_ids: frozenset[str] | None = None,
    ) -> None:
        self._config = config
        self._journal = journal
        self._lock = threading.RLock()
        self._visible_candidate_ids = visible_candidate_ids

    @property
    def config(self) -> HarnessConfig:
        """Read-only rendering configuration."""

        return self._config

    def restricted_to_candidates(self, candidate_ids: frozenset[str]) -> RulesStore:
        """A read view of this store exposing only the named candidates.

        Active rules stay fully visible — they are the validated baseline every
        read is entitled to. Only *provisional* rules are narrowed, which is what
        lets candidate validation attribute a replay's outcome: with one candidate
        visible, the replayed agent cannot be steered by five unrelated ones and
        have their combined effect scored as this candidate's verdict.

        The store is stateless over its JSONL file, so this is a cheap second
        instance rather than mutable state. Use it for reads; writes are unfiltered
        and belong on the primary store.
        """

        return RulesStore(
            self._config, journal=self._journal, visible_candidate_ids=candidate_ids
        )

    # -- reads ------------------------------------------------------------------

    def all(self) -> list[Rule]:
        """Latest record per rule id, ordered by creation time."""

        latest: dict[str, Rule] = {}
        for record in read_jsonl(self._config.rules_store_file):
            rule = Rule.from_json(record)
            if rule.id:
                latest[rule.id] = rule
        return sorted(latest.values(), key=lambda r: (r.created_at, r.id))

    def _readable(self, rules: list[Rule]) -> list[Rule]:
        """Apply the candidate restriction, if this is a restricted view."""

        hidden = self._visible_candidate_ids
        if hidden is None:
            return rules
        return [
            rule
            for rule in rules
            if rule.status != "candidate" or rule.id in hidden
        ]

    def active(self) -> list[Rule]:
        return [rule for rule in self.all() if rule.status == "active"]

    def candidates(self) -> list[Rule]:
        return [rule for rule in self.all() if rule.status == "candidate"]

    def live(self) -> list[Rule]:
        """Rules available to read: validated actives plus provisional candidates."""

        return self._readable(
            [rule for rule in self.all() if rule.status in ("active", "candidate")]
        )

    def register_scope_metadata(self, scope: str, description: str) -> None:
        """Persist authoritative bounded host metadata for a scope.

        Host metadata outranks an older persisted/derived description. The index
        is refreshed only when the scope is live, avoiding empty index entries.
        """

        wanted = normalize_scope(scope)
        clean = normalize_scope_description(description, scope=wanted)
        with self._lock:
            metadata = self._scope_metadata()
            existing = metadata.get(wanted)
            if existing == {"description": clean, "source": "host"}:
                return
            metadata[wanted] = {"description": clean, "source": "host"}
            atomic_write_json(self._config.scope_metadata_file, metadata)
            if any(rule.scope == wanted for rule in self.live()):
                self._sync_markdown_locked()

    def scope_index(self) -> list[dict[str, Any]]:
        """Structured equivalent of the compact task-facing index."""

        groups = self._grouped()
        descriptions = self._scope_descriptions(groups)
        return [
            {
                "scope": scope,
                "path": f"rules/{scope}.md",
                "description": descriptions[scope],
                "active": sum(rule.status == "active" for rule in rules),
                "provisional": sum(rule.status == "candidate" for rule in rules),
            }
            for scope, rules in groups.items()
        ]

    def _scope_metadata(self) -> dict[str, dict[str, str]]:
        raw = load_json(self._config.scope_metadata_file) or {}
        metadata: dict[str, dict[str, str]] = {}
        for raw_scope, raw_entry in raw.items():
            if not isinstance(raw_entry, dict):
                continue
            scope = normalize_scope(str(raw_scope))
            description = raw_entry.get("description")
            if not isinstance(description, str):
                continue
            metadata[scope] = {
                "description": normalize_scope_description(description, scope=scope),
                "source": str(raw_entry.get("source") or "persisted"),
            }
        return metadata

    def _scope_descriptions(
        self, groups: Mapping[str, Sequence[Rule]]
    ) -> dict[str, str]:
        metadata = self._scope_metadata()
        return {
            scope: (
                metadata[scope]["description"]
                if scope in metadata
                else normalize_scope_description(None, scope=scope)
            )
            for scope in groups
        }

    # -- retrieval ----------------------------------------------------------------

    def relevant(self, query: str | None, k: int) -> list[Rule]:
        """Active rules for a query: every ``global`` rule + the top-``k`` scoped.

        Selection is **per rule over the store**, never per file, so a large
        ``rules/scoped.md`` cannot degrade which rules get chosen. ``global``
        rules are always eligible and exempt from ``k`` (that is what the scope
        means); scoped rules rank by lexical relevance, and with no token overlap
        the ranking degrades to recency, so a fresh query never hides the whole
        rule set. ``query=None`` means "no signal" — everything is returned.
        """

        active = self.active()
        if query is None:
            return active
        query_tokens = _tokenize(query)
        global_rules = [rule for rule in active if rule.scope == GLOBAL_SCOPE]
        scoped = [rule for rule in active if rule.scope != GLOBAL_SCOPE]
        scores = {rule.id: _relevance(rule, query_tokens) for rule in scoped}
        return global_rules + _rank(scoped, scores)[: max(0, k)]

    def scopes(self) -> list[str]:
        """Distinct scopes with at least one live rule, in reading order.

        ``global`` first, then every other live scope
        alphabetically.
        """

        return list(self._grouped())

    def by_scope(self, scope: str) -> list[Rule]:
        """Live rules filed under ``scope`` — actives first, then candidates."""

        wanted = normalize_scope(scope)
        rules = [rule for rule in self.live() if rule.scope == wanted]
        return [r for r in rules if r.status == "active"] + [
            r for r in rules if r.status == "candidate"
        ]

    def search(
        self,
        query: str,
        *,
        limit: int = 10,
        statuses: Sequence[RuleStatus] = ("active",),
    ) -> list[tuple[Rule, float]]:
        """Rank rules of the given statuses by relevance to ``query``.

        Pure ranking — no global-rule special-casing — so everything beyond
        the context top-k stays reachable on demand.
        """

        wanted = set(statuses)
        pool = self._readable([rule for rule in self.all() if rule.status in wanted])
        query_tokens = _tokenize(query)
        scores = {rule.id: _relevance(rule, query_tokens) for rule in pool}
        return [(rule, scores[rule.id]) for rule in _rank(pool, scores)[: max(0, limit)]]

    def covering_rules(
        self,
        rule: str,
        *,
        scope: str,
        tags: Sequence[str] = (),
        failure_signatures: Sequence[str] = (),
    ) -> list[tuple[Rule, str]]:
        """Live rules that deterministically cover a proposed candidate."""

        wanted = normalize_scope(scope)
        covered: list[tuple[Rule, str]] = []
        for existing in self.live():
            reason = _coverage_reason(
                existing,
                text=rule,
                scope=wanted,
                tags=tags,
                failure_signatures=failure_signatures,
            )
            if reason is not None:
                covered.append((existing, reason))
        # Prefer a provisional already testing the same behavior, then the most
        # recent active. Either suppresses another candidate.
        covered.sort(key=lambda item: item[0].created_at, reverse=True)
        covered.sort(key=lambda item: item[0].status != "candidate")
        return covered

    # -- writes -----------------------------------------------------------------

    def add(
        self,
        rule: str,
        rationale: str,
        *,
        source_notice_id: str | None = None,
        metric: str | None = None,
        tags: Sequence[str] = (),
        scope: str = GLOBAL_SCOPE,
        applicability: RuleApplicability | None = None,
        failure_signatures: Sequence[str] = (),
        scope_description: str | None = None,
        suppress_similar: bool = False,
    ) -> Rule:
        """Record a new rule; idempotent on normalized text.

        With ``rule_validation`` on, the rule enters as a **candidate** (with
        its pre-trial baseline captured from the journal); otherwise it is
        ``active`` immediately. An explicitly configured positive
        ``max_active_rules`` raises ``RulesCapError`` at its bound; zero is
        unlimited and no rule is silently evicted.

        ``scope`` picks the ``rules/<scope>.md`` file the rule is written to. Any
        label is allowed and a new one simply creates a file. It defaults to
        ``global``: a caller with no basis for a narrower choice is stating that
        the rule is broadly applicable, not that it is unclassifiable.
        """

        max_len = self._config.sanitize_max_len
        clean_rule = sanitize_text(rule, max_len=max_len).strip()
        clean_rationale = sanitize_text(rationale, max_len=max_len).strip()
        if not clean_rule:
            raise ValueError("rule text must not be empty")

        status: RuleStatus = "candidate" if self._config.rule_validation else "active"
        # The baseline scans the journal; do it before taking the store lock.
        trial = self._capture_baseline(metric) if status == "candidate" else None

        wanted_scope = normalize_scope(scope)
        if applicability not in {"global", "topical", "task"}:
            if wanted_scope == GLOBAL_SCOPE:
                applicability = "global"
            elif wanted_scope == SCOPED_SCOPE:
                applicability = "task"
            else:
                applicability = "topical"
        clean_tags = _clean_tags(tags)
        clean_signatures = tuple(dict.fromkeys(str(value) for value in failure_signatures))[:16]

        with self._lock:
            live = self.live()
            for existing in live:
                reason = _coverage_reason(
                    existing,
                    text=clean_rule,
                    scope=wanted_scope,
                    tags=clean_tags,
                    failure_signatures=clean_signatures,
                )
                if reason == "exact_text" or (suppress_similar and reason is not None):
                    return existing
            cap = self._config.max_active_rules
            if cap > 0 and len(live) >= cap:
                raise RulesCapError(
                    f"live-rule cap ({cap}) reached; lifecycle validation or an "
                    "operator must retire a rule first"
                )
            entry = Rule(
                id=Rule.new_id(),
                created_at=_utcnow_iso(),
                rule=clean_rule,
                rationale=clean_rationale,
                source_notice_id=source_notice_id,
                metric=metric,
                status=status,
                tags=clean_tags,
                trial=trial,
                scope=wanted_scope,
                applicability=applicability,
                failure_signatures=clean_signatures,
            )
            append_jsonl(self._config.rules_store_file, entry.to_json())
            if scope_description:
                metadata = self._scope_metadata()
                metadata[wanted_scope] = {
                    "description": normalize_scope_description(
                        scope_description, scope=wanted_scope
                    ),
                    "source": "host",
                }
                atomic_write_json(self._config.scope_metadata_file, metadata)
            self._sync_markdown_locked()
        if self._journal is not None:
            self._journal.record({"type": "rule_add", **entry.to_json()})
        return entry

    def add_with_result(
        self, rule: str, rationale: str, **kwargs: Any
    ) -> tuple[Rule, bool]:
        """Atomically add and report whether this call created the record.

        The outer re-entrant lock closes the gap between an existence check and
        :meth:`add`, so concurrent repair episodes cannot both report ownership
        of the same exact or deterministically covered candidate.
        """

        with self._lock:
            before = {existing.id for existing in self.live()}
            result = self.add(rule, rationale, **kwargs)
            return result, result.id not in before

    def retire(
        self,
        rule_id: str,
        *,
        reason: str | None = None,
        trial: TrialState | None = None,
        validator: str | None = None,
        evidence: Mapping[str, Any] | None = None,
    ) -> Rule:
        """Retire a live (active or candidate) rule. Raises ``KeyError`` otherwise.

        ``trial`` lets a validator persist its verdict-stamped bookkeeping on
        the retired record, so ``harness_rule_status`` can explain why.
        ``validator`` and ``evidence`` are journaled alongside ``reason`` so a
        retirement can be audited structurally rather than by parsing prose — the
        per-case deltas that decided it are otherwise lost.
        """

        with self._lock:
            current = {rule.id: rule for rule in self.all()}
            rule = current.get(rule_id)
            if rule is None or rule.status == "retired":
                raise KeyError(f"rule {rule_id!r} is not a live rule")
            retired = replace(
                rule, status="retired", trial=trial if trial is not None else rule.trial
            )
            append_jsonl(self._config.rules_store_file, retired.to_json())
            self._sync_markdown_locked()
        if self._journal is not None:
            event: dict[str, Any] = {"type": "rule_retire", "id": rule_id}
            if reason:
                event["reason"] = reason
            if validator:
                event["validator"] = validator
            if evidence:
                event["evidence"] = dict(evidence)
            self._journal.record(event)
        return retired

    def promote(
        self,
        rule_id: str,
        *,
        reason: str = "",
        validator: str = "",
        trial: TrialState | None = None,
    ) -> Rule:
        """Promote a candidate to ``active``. Raises ``KeyError`` unless a candidate."""

        with self._lock:
            current = {rule.id: rule for rule in self.all()}
            rule = current.get(rule_id)
            if rule is None or rule.status != "candidate":
                raise KeyError(f"rule {rule_id!r} is not a candidate rule")
            promoted = replace(
                rule, status="active", trial=trial if trial is not None else rule.trial
            )
            append_jsonl(self._config.rules_store_file, promoted.to_json())
            self._sync_markdown_locked()
        if self._journal is not None:
            self._journal.record(
                {
                    "type": "rule_promote",
                    "reason": reason,
                    "validator": validator,
                    **promoted.to_json(),
                }
            )
        return promoted

    def update_trial(
        self, rule_id: str, mutate: Callable[[TrialState], TrialState]
    ) -> Rule:
        """Atomically update a candidate's trial bookkeeping (no journal event).

        ``mutate`` receives the FRESH trial state read under the store lock
        and returns the new one — a read-modify-write over a caller-held
        snapshot would let concurrent observers silently drop trial evidence.
        Returning the same object signals "no change" (nothing is appended).
        Trial updates are not journaled: one per observed session would drown
        the cross-run memory in bookkeeping noise.
        """

        with self._lock:
            current = {rule.id: rule for rule in self.all()}
            rule = current.get(rule_id)
            if rule is None or rule.status != "candidate":
                raise KeyError(f"rule {rule_id!r} is not a candidate rule")
            existing = rule.trial if rule.trial is not None else TrialState()
            trial = mutate(existing)
            if trial == existing and rule.trial is not None:
                return rule
            updated = replace(rule, trial=trial)
            append_jsonl(self._config.rules_store_file, updated.to_json())
        return updated

    def _capture_baseline(self, metric: str | None) -> TrialState:
        """Pre-candidate breach rate for the metric family, from the journal.

        The denominator is every session that appears in the recent ``notice``
        *and* ``recovery`` events — an approximation biased toward sessions
        that had incidents (fully-healthy sessions never journal either
        event), which biases the baseline rate HIGH. That makes the forward
        trial lenient about promotion, never about retirement; replay remains
        the strong evidence path.
        """

        started = _utcnow_iso()
        if self._journal is None:
            return TrialState(trial_started_at=started)
        events = self._journal.recent(
            limit=_BASELINE_WINDOW, types=("notice", "recovery")
        )
        sessions: set[str] = set()
        breached: set[str] = set()
        for event in events:
            session_id = str(event.get("session_id") or "")
            if not session_id:
                continue
            sessions.add(session_id)
            if event.get("type") != "notice":
                continue
            raw = event.get("signatures")
            signatures = [str(s) for s in raw] if isinstance(raw, list) else []
            if _matches_metric_family(signatures, metric):
                breached.add(session_id)
        return TrialState(
            baseline_breached_sessions=len(breached),
            baseline_sessions=len(sessions),
            baseline_window=len(events),
            trial_started_at=started,
        )

    # -- rendering ----------------------------------------------------------------

    def _grouped(self, live: Sequence[Rule] | None = None) -> dict[str, list[Rule]]:
        """Live rules bucketed by scope, in reading order, from one snapshot.

        Every renderer works off a grouping like this rather than re-querying: the
        store re-reads and re-parses the whole JSONL on each ``all()``, so rendering
        the root plus N scope files naively costs 2N+ full parses of identical data.
        """

        rules = list(live) if live is not None else self.live()
        groups: dict[str, list[Rule]] = {}
        for rule in rules:
            groups.setdefault(rule.scope, []).append(rule)
        for bucket in groups.values():
            bucket.sort(key=lambda r: r.status != "active")  # actives first
        ordered = [GLOBAL_SCOPE] if GLOBAL_SCOPE in groups else []
        ordered += sorted(set(groups) - {GLOBAL_SCOPE})
        return {scope: groups[scope] for scope in ordered}

    def render_root(self) -> str:
        """The **skill root**: the packaged instructions plus a References directory.

        Deliberately carries **no rule text**. The root is a stable read-only
        entry point — protocol, tool list, and a generated index of the rule files
        that exist — and rule content can be pulled on demand from ``rules/*.md``.
        """

        return self._root_from(self._grouped())

    def _root_from(self, groups: Mapping[str, Sequence[Rule]]) -> str:
        template = self._template()
        at = template.find(REFERENCES_MARKER)
        if at >= 0:
            head = template[: at + len(REFERENCES_MARKER)]
        else:
            # The packaged template always carries the marker; this only guards a
            # hand-edited one.
            head = template.rstrip() + "\n\n## References\n\n" + REFERENCES_MARKER
        return "\n".join(
            [
                head,
                "",
                *self._reference_lines(groups, self._scope_descriptions(groups)),
            ]
        ) + "\n"

    @staticmethod
    def _reference_lines(
        groups: Mapping[str, Sequence[Rule]], descriptions: Mapping[str, str]
    ) -> list[str]:
        if not groups:
            # Matches the packaged template's wording, so a freshly-seeded guide
            # and a regenerated empty one read identically.
            return ["_No learned rules are available yet._"]
        lines: list[str] = []
        for scope, rules in groups.items():
            active = sum(1 for r in rules if r.status == "active")
            provisional = len(rules) - active
            if lines:
                lines.append("")
            lines.extend(
                [
                    f"- [`{scope}`](rules/{scope}.md)",
                    f"  {descriptions[scope]}",
                    f"  {active} active, {provisional} provisional",
                ]
            )
        return lines

    def render_scope(self, scope: str, *, query: str | None = None) -> str:
        """One read-only rule file: active rules of ``scope``, then candidates.

        Candidates render under a clearly labeled provisional heading so an
        agent choosing to read the scope can distinguish them from active rules.
        Retrieval (when ``query`` is given) may narrow the actives, never the
        candidates.
        """

        wanted = normalize_scope(scope)
        return self._scope_from(wanted, self.by_scope(wanted), keep=self._keep_for(query))

    def _keep_for(self, query: str | None) -> set[str] | None:
        """The retrieval-selected active ids, or ``None`` for "keep everything".

        Hoisted out of the per-scope render because it is loop-invariant: the same
        query and top-k yield the same id set for every scope.
        """

        if not (self._config.rule_retrieval and query is not None):
            return None
        return {rule.id for rule in self.relevant(query, self._config.rules_context_topk)}

    def _scope_from(
        self, wanted: str, rules: Sequence[Rule], *, keep: set[str] | None = None
    ) -> str:
        active = [r for r in rules if r.status == "active"]
        candidates = [r for r in rules if r.status == "candidate"]

        selected = active if keep is None else [r for r in active if r.id in keep]
        omitted = len(active) - len(selected)

        lines = [f"# Rules — {wanted}", "", self._scope_intro(wanted), ""]
        if not active and not candidates:
            lines.append("_No learned rules yet._")
        for rule in selected:
            lines.extend(self._rule_bullet(rule))
        if omitted > 0:
            lines.append("")
            lines.append(
                f"_({omitted} more active rule(s) available — use "
                "harness_rules_search / harness_rules_list.)_"
            )
        if candidates:
            if selected or omitted:
                lines.append("")
            lines.append(PROVISIONAL_HEADING)
            lines.append("")
            lines.append(_PROVISIONAL_NOTE)
            lines.append("")
            for rule in candidates:
                lines.extend(self._rule_bullet(rule, provisional=True))
        return "\n".join(lines) + "\n"

    @staticmethod
    def _scope_intro(scope: str) -> str:
        if scope == GLOBAL_SCOPE:
            return (
                "_Broadly reusable rules, not tied to one task, workflow, "
                "application, tool, or domain._"
            )
        if scope == SCOPED_SCOPE:
            return (
                "_Specific rules for which no more meaningful stable scope could "
                "be determined._"
            )
        return f"_Rules learned in the context of `{scope}`._"

    def render_markdown(self, *, query: str | None = None) -> str:
        """The whole corpus in one string: the skill root plus every scope file.

        This is the *replay* context — what a candidate rule is validated against,
        and what a regression run replays with — so it must include candidates and
        every scope. It is not the bounded task-agent context rendered by
        ``hook.context``.
        """

        groups = self._grouped()
        keep = self._keep_for(query)
        return "\n".join(
            [
                self._root_from(groups),
                *(
                    self._scope_from(scope, rules, keep=keep)
                    for scope, rules in groups.items()
                ),
            ]
        )

    def _rule_bullet(self, rule: Rule, *, provisional: bool = False) -> list[str]:
        provenance = f", from notice {rule.source_notice_id}" if rule.source_notice_id else ""
        trial_note = ""
        if provisional and rule.trial is not None:
            observed = len(rule.trial.observed_sessions)
            needed = self._config.rule_trial_min_sessions
            trial_note = f"; trial: {observed}/{needed} sessions observed"
        label = f"**{rule.id}** (candidate)" if provisional else f"**{rule.id}**"
        return [
            f"- {label}: {rule.rule}",
            f"  - rationale: {rule.rationale} (added {rule.created_at}{provenance}{trial_note})",
        ]

    def sync_markdown(self) -> None:
        """Atomically regenerate the skill root and every ``rules/<scope>.md``."""

        with self._lock:
            self._sync_markdown_locked()

    def _sync_markdown_locked(self) -> None:
        # One snapshot for the whole sync: the root and every scope file are views
        # over the same rule set, and the store is locked, so re-reading per file
        # would re-parse identical data N+ times.
        cfg = self._config
        groups = self._grouped()
        atomic_write_text(cfg.rules_file, self._root_from(groups))
        for scope, rules in groups.items():
            atomic_write_text(cfg.rules_scope_file(scope), self._scope_from(scope, rules))
        # A scope whose every rule was retired keeps its file, rewritten empty, so
        # readers see "no rules here" rather than stale ones. Files are only
        # ever emptied, never unlinked because a prior context may reference one.
        if not cfg.rules_dir.is_dir():
            return
        for path in sorted(cfg.rules_dir.glob("*.md")):
            if path.stem in groups:
                continue
            empty = self._scope_from(path.stem, ())
            # Constant content once a scope is empty, so skip the rewrite rather
            # than churning the file on every later rule mutation.
            if _read_or_none(path) != empty:
                atomic_write_text(path, empty)
        if self._journal is not None:
            self._journal.record(
                {
                    "type": "scope_index_regenerated",
                    "path": "rules.md",
                    "scopes": [
                        {
                            "scope": scope,
                            "active": sum(rule.status == "active" for rule in rules),
                            "provisional": sum(
                                rule.status == "candidate" for rule in rules
                            ),
                        }
                        for scope, rules in groups.items()
                    ],
                }
            )

    def read_scope(self, scope: str) -> str:
        """Render one scope from the latest store records for task-facing reads.

        The persisted Markdown remains a recoverable artifact, but a long-lived
        process must not serve a stale file after another writer updates JSONL.
        """

        wanted = normalize_scope(scope)
        return self.render_scope(wanted)

    @staticmethod
    @lru_cache(maxsize=1)
    def _template() -> str:
        """The packaged skill-root template. Immutable, so read once per process."""

        resource = importlib.resources.files(_TEMPLATE_PACKAGE) / _TEMPLATE_NAME
        return resource.read_text(encoding="utf-8")

    # -- analysis -----------------------------------------------------------------

    def effectiveness(self) -> dict[str, dict[str, Any]]:
        """Per-rule notice counts before/after the rule was added.

        Computed from the journal's ``notice`` events for the rule's metric
        (all notices when the rule has no metric). Raw counts support operator
        review and managed-repair decisions.
        """

        if self._journal is None:
            return {}
        all_notices = self._journal.recent(limit=0, types=("notice",))
        result: dict[str, dict[str, Any]] = {}
        for rule in self.all():
            if rule.metric:
                events = self._journal.notices_for(rule.metric)
            else:
                events = all_notices
            before = sum(1 for e in events if str(e.get("ts", "")) < rule.created_at)
            after = sum(1 for e in events if str(e.get("ts", "")) >= rule.created_at)
            result[rule.id] = {
                "metric": rule.metric,
                "status": rule.status,
                "created_at": rule.created_at,
                "notices_before": before,
                "notices_after": after,
            }
        return result

    @staticmethod
    def _normalize(text: str) -> str:
        return " ".join(text.casefold().split()).rstrip(".!;,")


def _read_or_none(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return None
