"""Integration tests for the memory_nodes schema against a real PostgreSQL.

These require the throwaway test database (docker-compose.test.yml). Run them
via ``make test-integration``, which provisions it on port 5433.
"""

from __future__ import annotations

import uuid

import sqlalchemy as sa
from sqlalchemy import inspect, text

EXPECTED_COLUMNS = {
    "node_id",
    "parent_id",
    "session_id",
    "is_head",
    "framework_type",
    "payload",
    "created_at",
}

_INSERT = text(
    """
    INSERT INTO memory_nodes
        (node_id, parent_id, session_id, is_head, framework_type, payload)
    VALUES
        (:node_id, :parent_id, :session_id, :is_head, :framework_type, '{}'::jsonb)
    """
)


def test_table_and_columns_exist(migrated_engine):
    inspector = inspect(migrated_engine)
    assert "memory_nodes" in inspector.get_table_names()
    columns = {c["name"] for c in inspector.get_columns("memory_nodes")}
    assert columns == EXPECTED_COLUMNS


def test_expected_indexes_exist(migrated_engine):
    inspector = inspect(migrated_engine)
    index_names = {ix["name"] for ix in inspector.get_indexes("memory_nodes")}
    assert {"idx_session_head", "idx_parent_id"} <= index_names


def test_session_head_index_is_partial(migrated_engine):
    with migrated_engine.connect() as conn:
        indexdef = conn.execute(
            text("SELECT indexdef FROM pg_indexes WHERE indexname = 'idx_session_head'")
        ).scalar_one()
    assert "WHERE (is_head = true)" in indexdef


def test_server_defaults_applied(migrated_engine):
    node_id = str(uuid.uuid4())
    session_id = str(uuid.uuid4())
    with migrated_engine.begin() as conn:
        conn.execute(
            text(
                "INSERT INTO memory_nodes (node_id, session_id, framework_type, payload) "
                "VALUES (:node_id, :session_id, 'crewai', '{}'::jsonb)"
            ),
            {"node_id": node_id, "session_id": session_id},
        )
        row = conn.execute(
            text("SELECT is_head, created_at FROM memory_nodes WHERE node_id = :node_id"),
            {"node_id": node_id},
        ).one()
    assert row.is_head is False  # server_default false
    assert row.created_at is not None  # server_default NOW()


def test_foreign_key_cascade_deletes_descendants(migrated_engine):
    session_id = str(uuid.uuid4())
    root_id = str(uuid.uuid4())
    child_id = str(uuid.uuid4())

    with migrated_engine.begin() as conn:
        conn.execute(
            _INSERT,
            {
                "node_id": root_id,
                "parent_id": None,
                "session_id": session_id,
                "is_head": False,
                "framework_type": "langgraph",
            },
        )
        conn.execute(
            _INSERT,
            {
                "node_id": child_id,
                "parent_id": root_id,
                "session_id": session_id,
                "is_head": True,
                "framework_type": "langgraph",
            },
        )

    # Deleting the root must cascade to the child via ON DELETE CASCADE.
    with migrated_engine.begin() as conn:
        conn.execute(text("DELETE FROM memory_nodes WHERE node_id = :id"), {"id": root_id})

    with migrated_engine.connect() as conn:
        remaining = conn.execute(text("SELECT count(*) FROM memory_nodes")).scalar_one()
    assert remaining == 0


def test_models_match_migrations_no_drift(migrated_engine, alembic_config):
    from alembic import command

    # Raises AutogenerateDiffsDetected if the models and live schema differ.
    command.check(alembic_config)


def test_downgrade_removes_table(alembic_config, database_url):
    from alembic import command

    command.upgrade(alembic_config, "head")
    engine = sa.create_engine(database_url, future=True)
    try:
        assert "memory_nodes" in inspect(engine).get_table_names()
        command.downgrade(alembic_config, "base")
        assert "memory_nodes" not in inspect(engine).get_table_names()
    finally:
        engine.dispose()
        command.downgrade(alembic_config, "base")
